### ISSUE TITLE
who_depends_this_lib crashes with PermissionError

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/misc_scripts#9]
On build.archlinuxcn.org, run the following command as a normal user (e.g., yan12125):
```
LC_ALL=C PYTHONPATH=./winterpy/pylib ./who_depends_this_lib /data/repo/x86_64/archlinuxcn.files libicu
```
And the result is: (excerpted)
```
[I 10-30 14:33:49.244 who_depends_this_lib:47] extracting /data/repo/x86_64/vmware-workstation-15.0.0-2-x86_64.pkg.tar.xz...
[I 10-30 14:34:07.158 who_depends_this_lib:54] checking...
[W 10-30 14:34:07.246 who_depends_this_lib:58] /data/repo/x86_64/vmware-workstation-15.0.0-2-x86_64.pkg.tar.xz depends on libicudata.so.58: usr/lib/vmware-ovftool/libicuuc.so.58
Traceback (most recent call last):
  File "./who_depends_this_lib", line 117, in <module>
    main(args.pkgdb, re.compile(args.libname))
  File "./who_depends_this_lib", line 96, in main
    r, lib = check_package(os.path.join(dir, filename), lib_re)
  File "./who_depends_this_lib", line 59, in check_package
    return r, lib
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "./who_depends_this_lib", line 50, in extract_package
    yield d
  File "/usr/lib/python3.7/tempfile.py", line 805, in __exit__
    self.cleanup()
  File "/usr/lib/python3.7/tempfile.py", line 809, in cleanup
    _shutil.rmtree(self.name)
  File "/usr/lib/python3.7/shutil.py", line 485, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 423, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 423, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 423, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 443, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 441, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'hostd.ssl.config'
```

**Comment by lilydjwg** [comment]
Oops...Do you want to provide a fix? Maybe just call rm -rf.

**Comment by yan12125** [comment]
Sorry, but I don't have much time before 11/13. I can try it out then if you are willing to wait.
